_wandb:
    value:
        cli_version: 0.24.0
        e:
            mw8jzasnu6wrzqbc96zek7scstvc3nfc:
                cpu_count: 32
                cpu_count_logical: 64
                disk:
                    /:
                        total: "1888830910464"
                        used: "114188496896"
                email: lakshyaaagrawal@berkeley.edu
                executable: /data/home/lakshyaaagrawal/gepa/.venv/bin/python3
                git:
                    commit: 33f3c15576f19755f6f525c99a2141167e70aed3
                    remote: https://github.com/gepa-ai/gepa.git
                host: slurm-login-68b9cd64df-qvjnx
                memory:
                    total: "803131645952"
                os: Linux-6.8.0-1044-nvidia-x86_64-with-glibc2.35
                program: <python with no main file>
                python: CPython 3.14.3
                root: /data/home/lakshyaaagrawal/gepa
                startedAt: "2026-03-21T05:13:49.556580Z"
                writerId: mw8jzasnu6wrzqbc96zek7scstvc3nfc
        m:
            - "1": gepa/iteration
              "6":
                - 3
              "7": []
            - "2": gepa/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.14.3
        t:
            "3":
                - 2
                - 7
                - 13
            "4": 3.14.3
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
