_wandb:
    value:
        cli_version: 0.24.0
        e:
            zflvs8u0feczvwc5n1gw5j3b15wi2gx6:
                cpu_count: 32
                cpu_count_logical: 64
                disk:
                    /:
                        total: "1888830910464"
                        used: "256412389376"
                email: lakshyaaagrawal@berkeley.edu
                executable: /data/home/lakshyaaagrawal/gepa/.venv/bin/python3
                git:
                    commit: cb197d81afc7cf35f3be2acdaea7bacbe853b9d7
                    remote: https://github.com/gepa-ai/gepa.git
                host: slurm-login-68b9cd64df-qvjnx
                memory:
                    total: "803131645952"
                os: Linux-6.8.0-1044-nvidia-x86_64-with-glibc2.35
                program: /tmp/e2e_feature_tests.py
                python: CPython 3.14.3
                root: /data/home/lakshyaaagrawal/gepa
                startedAt: "2026-03-31T02:11:10.286528Z"
                writerId: zflvs8u0feczvwc5n1gw5j3b15wi2gx6
        m:
            - "1": train/step
              "6":
                - 3
              "7": []
            - "1": gepa/iteration
              "6":
                - 3
              "7": []
            - "2": gepa/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.14.3
        t:
            "1":
                - 95
            "2":
                - 95
            "3":
                - 2
                - 7
                - 13
                - 62
            "4": 3.14.3
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
gepa/frontier_type:
    value: hybrid
gepa/has_merge_proposer:
    value: false
gepa/perfect_score:
    value: null
gepa/raise_on_exception:
    value: true
gepa/run_dir:
    value: null
gepa/seed:
    value: 0
gepa/seed_candidate_components:
    value: '[''current_candidate'']'
gepa/track_best_outputs:
    value: true
gepa/trainset_size:
    value: 1
gepa/use_cloudpickle:
    value: true
gepa/val_evaluation_policy:
    value: FullEvaluationPolicy
gepa/valset_size:
    value: 1
