_wandb:
    value:
        cli_version: 0.24.0
        e:
            8gpgkc8q8ps5xe380sl8t2d75kuehirm:
                cpu_count: 32
                cpu_count_logical: 64
                disk:
                    /:
                        total: "1888830910464"
                        used: "114196787200"
                email: lakshyaaagrawal@berkeley.edu
                executable: /data/home/lakshyaaagrawal/gepa/.venv/bin/python3
                git:
                    commit: 23ebdea6208fec16b069d1093ce50f7e40133d28
                    remote: https://github.com/gepa-ai/gepa.git
                host: slurm-login-68b9cd64df-qvjnx
                memory:
                    total: "803131645952"
                os: Linux-6.8.0-1044-nvidia-x86_64-with-glibc2.35
                program: <python with no main file>
                python: CPython 3.14.3
                root: /data/home/lakshyaaagrawal/gepa
                startedAt: "2026-03-21T11:35:31.285578Z"
                writerId: 8gpgkc8q8ps5xe380sl8t2d75kuehirm
        m: []
        python_version: 3.14.3
        t:
            "2":
                - 95
            "3":
                - 2
                - 61
                - 62
            "4": 3.14.3
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
frontier_type:
    value: hybrid
has_merge_proposer:
    value: false
perfect_score:
    value: null
raise_on_exception:
    value: true
run_dir:
    value: null
seed:
    value: 0
seed_candidate_components:
    value: '[''current_candidate'']'
track_best_outputs:
    value: false
trainset_size:
    value: 1
use_cloudpickle:
    value: true
val_evaluation_policy:
    value: FullEvaluationPolicy
valset_size:
    value: 1
